apiVersion: v1
name: my-go-api
version: 1.0

appVersion: 1.0

description: A Helm chart for my Go REST API

maintainers:
- name: Subhradeep Ray
  email: subhradeepray2017@gmail.com

dependencies:
- name: my-database
  version: 1.0

# Define the resources that this chart creates
resources:
- name: my-go-api-deployment
  type: Deployment
  apiVersion: apps/v1
  metadata:
    name: my-go-api-deployment
    labels:
      app: my-go-api
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: my-go-api
    template:
      metadata:
        labels:
          app: my-go-api
      spec:
        containers:
        - name: my-go-api
          image: my-go-api:latest
          ports:
          - containerPort: 8080

# Define the services that this chart creates
services:
- name: my-go-api
  type: ClusterIP
  selector:
    app: my-go-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
